### PR TITLE
Fix NPE when tag key or value are null

### LINKED ISSUE #12: NPE from ApacheClientSpanDecorator
I'm seeing an NPE from this library when setting the hostname tag on a trace, I believe this only happens when the apache library is executing a retry?

    java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at io.opentracing.contrib.api.tracer.APIExtensionsSpan.handleSetTag(APIExtensionsSpan.java:214)
	at io.opentracing.contrib.api.tracer.APIExtensionsSpan.setTag(APIExtensionsSpan.java:194)
	at io.opentracing.tag.StringTag.set(StringTag.java:25)
	at io.opentracing.contrib.apache.http.client.ApacheClientSpanDecorator$StandardTags.onRequest(ApacheClientSpanDecorator.java:64)
	at io.opentracing.contrib.apache.http.client.TracingClientExec.handleNetworkProcessing(TracingClientExec.java:138)
	at io.opentracing.contrib.apache.http.client.TracingClientExec.execute(TracingClientExec.java:82)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)

The stack trace shows what is happening. I'm not sure why the url from apache would be null in the case of a retry but I don't think the library should cause the retry to explode with an NPE?

### PR DESCRIPTION
**Pull request by objectiser**
Fixes https://github.com/opentracing-contrib/java-apache-httpclient/issues/12

### CODE REVIEW

File: opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java [hunk 1]
```diff
@@ -230,9 +230,11 @@ public Span setTag(String key, Number value) {
     }
 
     private Span handleSetTag(String key, Object value) {
-        tags.put(key, value);
-        for (SpanObserver observer : observers) {
-            observer.onSetTag(this, key, value);
+        if (key != null && value != null) {
```
Comment (sjoerdtalsma) [inline opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java:233]: Are you sure that _both_ must be non-null?
While I understand the `key != null` condition, are you absolutely sure there is not somewhere, someone that has a usecase for tag value `null` ?
(could be, I'm not 100% on the spec)

File: opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java [hunk 2]
```diff
@@ -207,6 +209,22 @@ public void testOnSetTagBoolean() throws InterruptedException {
         }
     }
 
+    @Test
+    public void testOnSetTagNull() throws InterruptedException {
```
Comment (sjoerdtalsma) [inline opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java]: I'd split this in `testOnSetTagKeyNull` and `testOnSetTagValueNull` and verify that a `NullPointerException` must be fixed for both with the old code.

File: opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java (hunk 1 above)
Comment (objectiser) [reply opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java:233]: The Java OT API doesn't defined - but definitely key should not be null - and unclear how a null value would be represented, so should probably not be stored. However this change is only impacting whether the observer is informed - it still delegates the supplied values to the underlying tracer to handle how they wish.

One option would be to treat a null value as a remove - but generally tags are only set once.

File: opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java (hunk 2 above)
Comment (objectiser) [reply opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java]: Agree, once we have settled on the approach for handling null values.

File: opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java (hunk 1 above)
Comment (sjoerdtalsma) [reply opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java:233]: Agreed.

I just wanted to make sure it was a conscious choice, as this library is an 'automatic' wrapper, so might mess things up for wrapped tracers that operate on other assumptions.

I would be weary of limiting input if there's no inherent reason to do so, i.e. if the NPE is not from within the `java-api-extensions` library I would not restrict the input if it is not explicitly forbidden by the spec.

File: opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java [hunk 3]
```diff
@@ -230,9 +230,11 @@ public Span setTag(String key, Number value) {
...
+            tags.put(key, value);
```
Comment (yurishkuro) [inline opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java:234]: why does this class keep a copy of tags?

Comment (objectiser) [reply opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java:234]: Its to make the tags available to the observer.

File: opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java (hunk 1 above)
Comment (objectiser) [reply opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java:233]: Reduced scope of check on just the tags map - and included separate tests for key and value.

Comment (sjoerdtalsma) [reply opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java:233]: Looks like a decent solution, however from a pragmatic point of view maybe double-check whether your original objective is still fixed? 😉 
- https://github.com/opentracing-contrib/java-apache-httpclient/issues/12

I don't know whether the spec allows `null` keys? What would they mean?

Comment (objectiser) [reply opentracing-api-extensions-tracer/src/main/java/io/opentracing/contrib/api/tracer/APIExtensionsSpan.java:233]: The tests reproduced the problem - so should be fine.
The spec doesn't make it clear - but atleast now it is delegated to the tracer and observer to handle :)

File: opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java [hunk 4]
```diff
@@ -207,6 +208,38 @@ public void testOnSetTagBoolean() throws InterruptedException {
...
+        Span testSpan = spanFactory.create();
+        APIExtensionsSpan span = new APIExtensionsSpan(testSpan, null,
+                0, 0, new ConcurrentHashMap<String, Object>());
+        SpanObserver observer = Mockito.mock(SpanObserver.class);
+        span.addSpanObserver(observer);
+
+        span.setTag((String)null, "testvalue");
+
+        verify(observer).onSetTag(span, null, "testvalue");
+        if (testSpan != null) {
```
Comment (pavolloffay) [inline opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java:222]: Is this null check necessary?

File: opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java [hunk 5]
```diff
@@ -207,6 +208,38 @@ public void testOnSetTagBoolean() throws InterruptedException {
...
+        Span testSpan = spanFactory.create();
+        APIExtensionsSpan span = new APIExtensionsSpan(testSpan, null,
+                0, 0, new ConcurrentHashMap<String, Object>());
+        SpanObserver observer = Mockito.mock(SpanObserver.class);
+        span.addSpanObserver(observer);
+
+        span.setTag("testkey", (String)null);
+
+        verify(observer).onSetTag(span, "testkey", null);
+        if (testSpan != null) {
```
Comment (pavolloffay) [inline opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java:238]: The same as above

**Review by pavolloffay — APPROVED** [review]

File: opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java (hunk 4 above)
Comment (objectiser) [reply opentracing-api-extensions-tracer/src/test/java/io/opentracing/contrib/api/tracer/APIExtensionsSpanTest.java:222]: Yes, because the tests are run twice, once with a null span.
